QF-1546 - Added UpdateAparSummary function
SkillsFundingAgency/das-assessor-functions pull request #106
Opened 2023-07-18 13:44 UTC by PeterDavidWilliams

2023-08-02 10:42 UTC, ChrisJWoodcock requested changes

2023-08-02 10:42 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions.ExternalApis/Assessor/IAssessorServiceApiClient.cs
> +        Task UpdateAssessmentOrganisationsList();
Should be UpdateAparSummary

2023-08-03 13:53 UTC, SarahDuncan commented on src/SFA.DAS.Assessor.Functions/Domain/Assessors/AssessmentOrganisationsListUpdateCommand.cs
> +    {
naming

2023-08-03 13:53 UTC, SarahDuncan commented on src/SFA.DAS.Assessor.Functions/Domain/Assessors/Interfaces/IAssessmentOrganisationsListUpdateCommand.cs
> +    {
naming

2023-08-03 13:53 UTC, SarahDuncan commented on src/SFA.DAS.Assessor.Functions/Functions/Assessors/AssessmentOrganisationsListUpdateFunction.cs
> +        [FunctionName("AssessmentOrganisationsListUpdate")]
should we change the function name

2023-09-14 09:33 UTC, ChrisJWoodcock approved these changes

2023-10-04 11:11 UTC, merged