CON-2185-bring api sandbox to funcation app.
SkillsFundingAgency/das-assessor-functions pull request #35
Opened 2020-09-10 16:23 UTC by shomavg

2020-09-11 08:46 UTC, ChrisJWoodcock requested changes
You can't just copy this across from one place to another you need to make it fit with how the new function library works for configuration, logging function names, trigger time configuration etc...

2020-09-11 08:46 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions.Infrastructure/ConfigurationHelper.cs
> +        public static IWebConfiguration GetConfiguration()
What is this???

2020-09-11 13:58 UTC, ChrisJWoodcock requested changes
Just a few minor tweaks needed

2020-09-11 13:58 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions/Startup.cs
> +            builder.Services.Configure<ExternalApiDataSyncConfig>(config.GetSection("ExternalApiDataSyncConfig"));
Remove Config word from here if you can

2020-09-11 13:58 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions/Functions/ExternalApiDataSync/ExternalApiDataSyncFunction.cs
> +        public async Task Run([TimerTrigger("%ExternalApiDataSyncFunctionSchedule%", RunOnStartup = true)]TimerInfo myTimer, ILogger log, ExecutionContext context)
This "ExternalApiDataSyncFunctionSchedule" is defined in another file with an actual schedule - which you have from the original code - you can't see that when the project is load - swap to directory view

2020-09-16 17:18 UTC, ChrisJWoodcock requested changes

2020-09-16 17:18 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions.ExternalApis/Assessor/AssessorServiceApiClient.cs
> +        public async Task ExternalApiDataSync(GetDataSyncRequest getDataSyncRequest)
RebuildExternalApiSandbox?

2020-09-16 17:18 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions/Functions/ExternalApiDataSync/ExternalApiDataSyncFunction.cs
> +namespace SFA.DAS.Assessor.Functions.Functions.ExternalApiDataSync
RebuildExternalApiSandboxFunction?? - seems like a better name - and you are free to rename it here - just make everything else follow along

2020-09-16 17:18 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions/Functions/ExternalApiDataSync/ExternalApiDataSyncFunction.cs
> +        public async Task Run([TimerTrigger("%ExternalApiDataSyncFunctionSchedule%", RunOnStartup = true)]TimerInfo myTimer, ILogger log, ExecutionContext context)
Don't forget the other files for this schedule need to be amended to include the default schedule

2020-09-16 17:19 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions/Functions/ExternalApiDataSync/ExternalApiDataSyncFunction.cs
> +                await _assessorServiceApi.ExternalApiDataSync(dataSyncRequest);
use the standard command pattern here even when it does almost nothing - for consistency

2020-09-17 16:43 UTC, ChrisJWoodcock requested changes

2020-09-17 16:43 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions.ExternalApis/Assessor/AssessorServiceApiClient.cs
> +            using (var request = new HttpRequestMessage(HttpMethod.Post, $"/api/v1/externalapidatasync"))
You can change the url as well to make it clearer

2020-09-17 16:43 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions/Functions/ExternalApiDataSync/RebuildExternalApiSandboxFunction.cs
> +        public async Task Run([TimerTrigger("%RebuildExternalApiSandboxFunctionSchedule%", RunOnStartup = true)]TimerInfo myTimer, ILogger log, ExecutionContext context)
Should not have RunOnStartup for this

2020-09-17 16:43 UTC, ChrisJWoodcock commented on azure/template.json
> +        "description": "RebuildExternalApiSandboxFunction CRON Schedule e.g. 0 */15 * * * *"
e.g. should be the default I think

2020-09-17 16:43 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions/Startup.cs
>              builder.Services.AddTransient<IPrintProcessCommand, PrintProcessCommand>();
I think your new command should be here?

2020-09-18 10:35 UTC, ChrisJWoodcock approved these changes

2020-11-26 16:44 UTC, cofaulco approved these changes

2020-12-04 13:23 UTC, merged