Con 2263
SkillsFundingAgency/das-assessor-functions pull request #42
Opened 2020-10-21 08:28 UTC by hkf-tech

2020-10-22 10:12 UTC, ChrisJWoodcock requested changes

2020-10-22 10:12 UTC, ChrisJWoodcock commented on src/SFA.DAS.Assessor.Functions/Domain/Print/PrintProcessCommand.cs
> +                await _scheduleService.UpdateLastRunStatus(schedule, ExternalApis.Assessor.Types.LastRunStatus.Started);
When a schedule is Completed - it is done in the ScheduleService - so why not have the Start and Fail in that service as well?

2020-10-22 10:20 UTC, hkf-tech commented on src/SFA.DAS.Assessor.Functions/Domain/Print/PrintProcessCommand.cs
> +                await _scheduleService.UpdateLastRunStatus(schedule, ExternalApis.Assessor.Types.LastRunStatus.Started);
I will make this change - will move Fail & start to ScheduleService

2020-10-22 10:22 UTC, hkf-tech commented on src/SFA.DAS.Assessor.Functions/Domain/Print/PrintProcessCommand.cs
> +                await _scheduleService.UpdateLastRunStatus(schedule, ExternalApis.Assessor.Types.LastRunStatus.Started);
> Are we considering what to do if the status isn't as we expect it when we go to update it?

schedule = await _scheduleService.Get(); (on line 57) gets the schedule with the desired status,  haven't made further checks.

2020-10-23 14:53 UTC, cofaulco approved these changes

2020-10-26 10:16 UTC, ChrisJWoodcock approved these changes

2020-11-18 09:41 UTC, merged